server:
  port: 8989

spring:
  application:
    name: training-system
  
  datasource:
    url: jdbc:mysql://1Panel-mysql-g6lU:3306/training_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update  # 生产环境使用update模式
    show-sql: false  # 生产环境关闭SQL日志
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    defer-datasource-initialization: false  # 生产环境不执行SQL初始化
  
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# JWT配置
jwt:
  secret: ${JWT_SECRET:trainingSystemSecretKey2024}  # 建议通过环境变量设置
  expiration: 86400000 # 24小时

# 文件上传配置
file:
  upload-dir: /app/uploads/  # 生产环境使用绝对路径
  allowed-types: jpg,jpeg,png,gif,mp4,avi,mov
  max-size: 100MB

# 日志配置
logging:
  level:
    com.training: ERROR
    org.springframework.security: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    org.springframework.boot: ERROR
    root: ERROR
  file:
    name: /app/logs/training-system.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 